- topic_name: /x500/camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- topic_name: /x500/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: BIDIRECTIONAL

- topic_name: /x500/gimbal_camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- topic_name: /x500/gimbal_segmentation_camera/colored_map
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- topic_name: /x500/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- topic_name: /x500/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS

# TF frames (from PosePublisher plugin on x500 model)
- gz_topic_name: /model/x500/pose
  ros_topic_name: /tf
  gz_type_name: gz.msgs.Pose_V
  ros_type_name: tf2_msgs/msg/TFMessage
  direction: GZ_TO_ROS

